{
    "id": "py_api_error",
    "language": "python2",
    "code": "def run():\n\ttry: clotho.bogus()\n\texcept ClothoError as e: return 'caught ClothoError: {}'.format(e.args[0])\n\traise RuntimeException('this is very bad; please fix me')"
}
